# Generated by Django 4.2.3 on 2023-08-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmer', to='query.company'),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='programmers', to='query.language'),
        ),
    ]
